### ISSUE TITLE
Dataurl points to an old S3 bucket

### ISSUE THREAD

**Issue by nswanberg** [poldrack/myconnectome#11]
Thanks for the reproduceable environment and the Vagrant VM. The VM errors and stops at get_list_data in get_data_.py, probably because the code here is pointing to old S3 buckets.

The variable dataurl in https://github.com/poldrack/myconnectome/blob/master/myconnectome/utils/get_data.py points to http://s3.amazonaws.com/openfmri/ds031/myconnectome-vm, which has no data, while in http://results.myconnectome.org/results/myconnectome/myconnectome/utils/get_data.py it points to http://s3-us-west-2.amazonaws.com/myconnectome/base, which has data in it.

**Comment by poldrack** [comment]
weird, just worked last week.  will have a look and try to fix ASAP

**Comment by erikssona** [comment]
I had the same issue.

**Comment by vsoch** [comment]
Just a quick note here - it was indeed an old S3 bucket, [here are details](https://github.com/poldrack/myconnectome-vm/issues/15#issuecomment-168108445) if you want a quick workaround to get things running, and please let us know if you have additional difficulties. Happy New Year!

**Comment by poldrack** [comment]
please try it again (using the main branch, not vanessa's branch).  there were some data missing and permissions issues on the openfmri bucket that I think should be fixed now

**Comment by erikssona** [comment]
It's fixed.
