### ISSUE TITLE
downloading the data from openfmri

### ISSUE THREAD

**Issue by echohenry2006** [poldrack/myconnectome#12]
Thank you for sharing  such a valuable data!! But when I tried to download the data from openfmri, I got some error pages which  reads like 

"This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error slick-uniqueid="3">

<div>
<a id="slick_uniqueid"/>
</div>

<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>tarballs/ds031_set01.tgz</Key>
<RequestId>62500D252A476A9C</RequestId>
<HostId>
VZy4VO51xGMImBiwT3AyziEbTmOThX2Ft9QwZVBQacdLwlHvcmRG12GZpIhGSH2P
</HostId>
</Error>"

Could help to fix this problem?

Thanks very much!

**Comment by poldrack** [comment]
this is because the file names have changed from .tgz to .tar - can you tell me which download function you are using?

**Comment by poldrack** [comment]
I see - the download links are incorrect on openfmri, will fix them asap. you can find the correct links here:  http://myconnectome.org/wp/data-sharing/

**Comment by poldrack** [comment]
links on openfmri.org have been fixed
