### ISSUE TITLE
Data links in readme file

### ISSUE THREAD

**Issue by erikssona** [poldrack/myconnectome#14]
The links in the Readme on RNA Postprocessing don't work for me. Perhaps it's a permissions issue again? I'm referring to myconnectome/myconnectome/rnaseq/README.md

**Comment by poldrack** [comment]
sorry about that - can you please provide more detailed error messages?

**Comment by erikssona** [comment]
The amazon links just go to empty xml files. I can screenshot them later if
that helps, but it's the same problem we had with the data access
previously.

**Comment by erikssona** [comment]
![image](https://cloud.githubusercontent.com/assets/2542049/12538727/364120c8-c296-11e5-934f-90c2b81b3777.png)

**Comment by poldrack** [comment]
thanks -where exactly do these links appear?

**Comment by erikssona** [comment]
[In this readme file.](https://github.com/poldrack/myconnectome/blob/master/myconnectome/rnaseq/README.md)

**Comment by poldrack** [comment]
gotcha, sorry, that page needs a complete overhaul. which specific file are you trying to find?

**Comment by erikssona** [comment]
The preprocessed RNA-Seq data. I'm looking for expression counts.

**Comment by poldrack** [comment]
for preprocessed data, you can look here:(http) http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE58122&format=file&file=GSE58122%5Fvarstab%5Fdata%5Fprefiltered%5Fgeo%2Etxt%2Egz&token=yfqzaooshpijdsn
for the individual session files, you can find them here: http://web.stanford.edu/group/poldracklab/myconnectome-data/base/rna-seq/
cheers
rp

**Comment by erikssona** [comment]
I might be missing something, but how do the sub labels correspond to the draw dates?

**Comment by poldrack** [comment]
see the drawdates.txt and pathsubs.txt files at http://web.stanford.edu/group/poldracklab/myconnectome-data/base/rna-seq/
